from __future__ import annotations

import json
import re
from fractions import Fraction
from pathlib import Path


BP_LABEL_BLOCK_RE = re.compile(r"labels := \[\*(.*?)\*\];", re.S)
BP_DATA_BLOCK_RE = re.compile(r"data := \[\*(.*?)\*\];", re.S)
BP_LABEL_RE = re.compile(r'"(\d+\.[a-z]+\.\d+\.\d+)"')
BP_ENTRY_RE = re.compile(r"\[\*\s*\[\*(.*?)\*\]\s*,\s*\[\*(.*?)\*\]\s*\*\]", re.S)


def parse_bp_file(path: Path) -> list[dict[str, object]]:
    text = path.read_text(encoding="utf-8")

    labels_match = BP_LABEL_BLOCK_RE.search(text)
    data_match = BP_DATA_BLOCK_RE.search(text)
    if not labels_match or not data_match:
        raise ValueError(f"Could not parse labels/data blocks from {path}")

    labels = BP_LABEL_RE.findall(labels_match.group(1))
    entries = BP_ENTRY_RE.findall(data_match.group(1))
    if len(labels) != len(entries):
        raise ValueError(
            f"Label/data count mismatch in {path}: {len(labels)} labels vs {len(entries)} data entries"
        )

    curves: list[dict[str, object]] = []
    for label, (f_block, h_block) in zip(labels, entries):
        f_coeffs = [int(part.strip()) for part in f_block.split(",") if part.strip()]
        h_coeffs = [int(part.strip()) for part in h_block.split(",") if part.strip()]
        curves.append({"label": label, "f_coeffs": f_coeffs, "h_coeffs": h_coeffs})
    return curves


def parse_modular_json_dir(path: Path) -> list[dict[str, object]]:
    curves: list[dict[str, object]] = []
    for json_file in sorted(path.glob("*.json")):
        payload = json.loads(json_file.read_text(encoding="utf-8"))
        wm = payload.get("weierstrass_model")
        if not wm or not wm.get("equation"):
            continue

        eq_str = wm["equation"].strip()
        if not (eq_str.startswith("[") and eq_str.endswith("]")):
            raise ValueError(f"Unexpected weierstrass equation format in {json_file}")
        h_raw, f_raw = eq_str[1:-1].split(",", 1)
        h_raw = h_raw.strip()
        f_raw = f_raw.strip()

        h_coeffs = poly_str_to_coeffs(h_raw)
        f_coeffs = poly_str_to_coeffs(f_raw)
        curves.append(
            {
                "label": payload["label"],
                "h_coeffs": h_coeffs,
                "f_coeffs": f_coeffs,
            }
        )
    return curves


def poly_str_to_coeffs(poly: str) -> list[Fraction]:
    expr = poly.replace(" ", "")
    if expr == "":
        return [Fraction(0)]

    expr = expr.replace("-", "+-")
    if expr.startswith("+-"):
        expr = expr[1:]
    terms = [term for term in expr.split("+") if term]

    coeffs_by_exp: dict[int, Fraction] = {}
    for term in terms:
        if "x" not in term:
            coeff = Fraction(term)
            exp = 0
        else:
            if "*x^" in term:
                coeff_str, exp_str = term.split("*x^")
                coeff = Fraction(coeff_str)
                exp = int(exp_str)
            elif term.endswith("x") and "*x" in term:
                coeff_str = term[:-2]
                coeff = Fraction(coeff_str)
                exp = 1
            elif term == "x":
                coeff = Fraction(1)
                exp = 1
            elif term == "-x":
                coeff = Fraction(-1)
                exp = 1
            elif term.startswith("x^"):
                coeff = Fraction(1)
                exp = int(term[2:])
            elif term.startswith("-x^"):
                coeff = Fraction(-1)
                exp = int(term[3:])
            else:
                raise ValueError(f"Unsupported polynomial term: {term!r}")
        coeffs_by_exp[exp] = coeffs_by_exp.get(exp, Fraction(0)) + coeff

    max_exp = max(coeffs_by_exp, default=0)
    coeffs = [coeffs_by_exp.get(exp, Fraction(0)) for exp in range(max_exp, -1, -1)]
    while len(coeffs) > 1 and coeffs[0] == 0:
        coeffs.pop(0)
    return coeffs


def magma_fraction(value: Fraction) -> str:
    return str(value.numerator) if value.denominator == 1 else f"{value.numerator}/{value.denominator}"


def magma_coeff_list(coeffs: list[int] | list[Fraction]) -> str:
    return "[ " + ", ".join(magma_fraction(Fraction(c)) for c in coeffs) + " ]"


def magma_quote(value: str) -> str:
    return '"' + value.replace('"', '\\"') + '"'


def write_magma_input(
    bp_curves: list[dict[str, object]],
    modular_curves: list[dict[str, object]],
    output_path: Path,
) -> None:
    lines: list[str] = []
    lines.append("// Auto-generated by build_bp_modular_rank2_magma_input.py")
    lines.append("bp_curves := [*")
    for curve in bp_curves:
        lines.append(
            "    <{label}, {h_coeffs}, {f_coeffs}>,"
            .format(
                label=magma_quote(curve["label"]),  # type: ignore[arg-type]
                h_coeffs=magma_coeff_list(curve["h_coeffs"]),  # type: ignore[arg-type]
                f_coeffs=magma_coeff_list(curve["f_coeffs"]),  # type: ignore[arg-type]
            )
        )
    lines.append("*];")
    lines.append("")
    lines.append("modular_curves := [*")
    for curve in modular_curves:
        lines.append(
            "    <{label}, {h_coeffs}, {f_coeffs}>,"
            .format(
                label=magma_quote(curve["label"]),  # type: ignore[arg-type]
                h_coeffs=magma_coeff_list(curve["h_coeffs"]),  # type: ignore[arg-type]
                f_coeffs=magma_coeff_list(curve["f_coeffs"]),  # type: ignore[arg-type]
            )
        )
    lines.append("*];")
    lines.append("")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    root = Path(__file__).resolve().parent
    bp_path = root / "data" / "bianchi_padurariu" / "BiellipticGenus2List.m"
    modular_dir = root / "data" / "genus2" / "curves_data_rank_2"
    output_path = root / "bp_modular_rank2_input.m"

    bp_curves = parse_bp_file(bp_path)
    modular_curves = parse_modular_json_dir(modular_dir)
    write_magma_input(bp_curves, modular_curves, output_path)

    print(f"Wrote {len(bp_curves)} BP curves and {len(modular_curves)} modular curves to {output_path}")


if __name__ == "__main__":
    main()
